### ISSUE TITLE
Use of plugins for chage skills

### ISSUE THREAD

**Issue by macetti8** [lepoetemaudit/percentageloader#1]
Hi,

first I would like to tell you that your plugin it's amazing, I love it.
I would like to know if you can tell me same advise about how to make multiple percentageloader
for charge mi skills, I was triyng to work on them but something does not work.

I would like use your plugin for charge for example my skills on HTML,CSS,Drupal etc so each element should has different percentual; I'm not so expert on this topic so if you can give some advise will be nice.

Thank you very much

**Comment by lepoetemaudit** [comment]
Hi, thanks for using! You may have hit a bug; I'm working on a proper release of version 0.2 and I recently transferred it from its original home on bitbucket: https://bitbucket.org/Better2Web/jquery.percentageloader which for now you should consider as the stable release. There is demo code that shows you how to use multiple loaders here: http://widgets.better2web.com/loader If you are asking how to customise the look and feel of the percentage loader, this isn't possible yet, but it's on the roadmap.
