### ISSUE TITLE
  Violates Content Security Policy

### ISSUE THREAD

**Issue by niraj315** [lepoetemaudit/percentageloader#8]
Getting Error for Content Security Policy Violation at line no. 21 for **imgdata** variable.

> > jquery.percentageloader-0.2.js:21 Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAA and so on...
> > img-src https://_mywebsite.com_".

**Comment by lepoetemaudit** [comment]
That's interesting - what browser is this happening on? Also, are you opening an HTML file locally directly or are you using some sort of server? Sometimes browsers are funny when opening static HTML with how they handle assets.

However, the image data is being populated via Javascript so it shouldn't violate cross-domain policy...

**Comment by niraj315** [comment]
Hi Dave, I don't know what happened but it fixed now! I was getting this error on gc and ff browsers, and it was from server. How ever now it disappears! 
Thanks for reply.
