### ISSUE TITLE
setProgress not working

### ISSUE THREAD

**Issue by Emyleen** [lepoetemaudit/percentageloader#9]
When I use the plugin like this : 

`var $slide = $(this);

```
var loader = $slide.find('.avatar-spinner').percentageLoader({
    valElement: '.slide-percent',
    strokeWidth: 10,
    bgColor: '#dcdcdc',
    ringColor: '#5cb85c',
    textColor: '#333333',
    fontSize: '1.5em',
    fontWeight: '500',
    controllable: true,
    progress: 0
});


setTimeout(function(){
    loader.setProgress(maxTime / 100);
}, 100);`
```

I have a console error in the setTimeout the variable loader doesn't exist. Can you tell me why? Thank you.

**Comment by lepoetemaudit** [comment]
Do you have the exact error the console gave you? And if possible the full file? Your code looks fine but if it says the loader variable doesn't exist (undefined?) it's probably a variable scope issue.

That said, this plugin is not very well maintained now (my bad, as I no longer touch jQuery at all) so it's not always a very good jQuery citizen.
